require 'httparty'
require 'ostruct'
require 'forwardable'

require 'closeio/base'
require 'closeio/contact'
require 'closeio/email_activity'
require 'closeio/email_template'
require 'closeio/lead'
require 'closeio/note_activity'
require 'closeio/organization'
require 'closeio/paginated_list'
require 'closeio/report'
require 'closeio/saved_search'
require 'closeio/task'
require 'closeio/version'
